name: Generate bioconda plots

on:
  schedule:
  - cron: '0 5,23 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Update submodule
      run: |
        git pull --no-recurse-submodules
        git submodule foreach git fetch --tags
        git submodule foreach git config remote.origin.fetch '+refs/heads/data:refs/remotes/origin/data'
        git submodule update --remote --recursive

    - name: Generate plots
      run: |
        pip install GitPython pandas
        export PYTHONPATH="$( pwd )/src"
        python -m build_plots.plot_cdf
        python -m build_plots.plot_versions
        python -m build_plots.plot_platforms

    - name: Add changes, commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git status
        git commit -m 'Update bioconda plots and submodule' || echo "No changes to commit"

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Push changes
      run: |
        git push

