name: Generate bioconda plots

on:
  schedule:
  - cron: '0 5,23 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Update submodule
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
      
    - name: Generate plots
      run: |
        python src/plot_cdf.py
        python src/plot_versions.py
        
    - name: Add changes, commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A ./plots
        git status
        git commit -m 'Update bioconda plots and submodule'
        
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: Push changes
      run: |
        git push

