name: Test bioconda plot generation

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Fetch submodule tags
      run: |
        git submodule foreach git fetch --tags

    - name: Generate plots
      run: |
        pip install GitPython pandas
        export PYTHONPATH="$( pwd )/src"
        python -m build_plots.plot_cdf
        python -m build_plots.plot_versions 5 100
        python -m build_plots.plot_platforms 5 100
